
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/squad?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 'rnjsxkr534'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect

    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: #

jwt:
  secret: helloworld4522!@#$

discord:
  id: 1159029609552171049
  secret: iC2Tju-1xkBXuSwqzbbZDsr5OG3MpMoL
  redirect: http://localhost:3000/discord
