CREATE DATABASE squad;

CREATE TABLE user(
	uuid VARCHAR(255) PRIMARY KEY,
	nickname VARCHAR(255) NOT NULL,
	tag VARCHAR(10) NOT NULL,
	email VARCHAR(255),
	avatar_url VARCHAR(255)
);

CREATE TABLE post (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	writer VARCHAR(255) NOT NULL,
	map VARCHAR(100) NOT NULL,
	`server` VARCHAR(100) NOT NULL,
	memo VARCHAR(255) NOT NULL,
	created DATETIME NOT NULL,

	FOREIGN KEY (writer) REFERENCES user(`uuid`)
		ON DELETE CASCADE
);